@startsalt
{
  ReCenso da BackByte 📊 
{T#
+Densidade Demográfica 👥       | 4,45 hab/km³   
+ População   👤     | 7.13 mil habitantes 
+ Mortalidade  ☠️  | 7,5 
+ Nivel de Instrução | Ensino médio completo
+ Taxa de Natalidade | 1,7
}

[Gráficos] 
[Estatísticas 📈]
..
}
@endsalt

